# Generated by Django 4.1.13 on 2026-02-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('border_name', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'borders',
            },
        ),
        migrations.CreateModel(
            name='DashboardCount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('borders', models.IntegerField(blank=True, null=True)),
                ('border_crossed', models.IntegerField(blank=True, null=True)),
                ('fishing_zones', models.IntegerField(blank=True, null=True)),
                ('emergencies', models.IntegerField(blank=True, null=True)),
                ('fishermans', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboard_count',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(blank=True, choices=[('Fisherman', 'Fisherman'), ('ADMIN', 'ADMIN')], max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='FishPotentials',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fish_name', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='fisher_man.user')),
            ],
            options={
                'db_table': 'fish_potentials',
            },
        ),
        migrations.CreateModel(
            name='EmergencyRequests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emergency_note', models.TextField(blank=True, null=True)),
                ('action_taken', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='fisher_man.user')),
            ],
            options={
                'db_table': 'emergency_requests',
            },
        ),
        migrations.CreateModel(
            name='BorderCrossedLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='fisher_man.user')),
            ],
            options={
                'db_table': 'border_crossed_logs',
            },
        ),
    ]
